### ISSUE TITLE
npm install fails with latest node / npm

### ISSUE THREAD

**Issue by gr2m** [kahlil/tinydraft-preact-cli#1]
See https://gist.github.com/4dd749108bc806257a6574af38bd1c73
I tried Node 6.9.1 / npm 3.10.10, too, but it failed as well

**Comment by khalillechelt** [comment]
@gr2m OK I pushed the code it just adds the code that tries to sign up  the account. I get the weird `process` error again...

Just pull and start the app up again to reproduce.

**Comment by gr2m** [comment]
I’ll have a look tomorrow 👍

**Comment by gr2m** [comment]
hey what’s latest? I’ve seen you got it to create a user account (https://twitter.com/kahliltweets/status/870655051211190274), when I run `npm start` I still get the `ReferenceError: process is not defined`

**Comment by khalillechelt** [comment]
Seems to work I'll push something tomorrow. It's Firetag in the DE today 😉
